### ISSUE TITLE
Occasionally gets randomly stuck loading the list of reading lists. 

### ISSUE THREAD

**Issue by e-e-e** [e-e-e/hyper-reader#37]
This happens when one of the hyper-readings archives is broken or fails to load.

To fix this we should add a timeout for loading an archive.

But for now if you experience this issue just delete or move your archives from `~/hyper-readings/`.

You can find the offending list by removing them from the directory one at a time.

**Comment by e-e-e** [comment]
offending list is currently - @equivalentideas'
 `eb584b090c6160250e2b39285518e553f9fb0e7867536eabeb50310c7da9bbd7`
Not sure why, but even when importing it - it gets stuck.

**Comment by e-e-e** [comment]
Looks like this is related to the interaction with hyper-graph-db - it does not fire the ready event until the graph has downloaded all necessary content - eg: name, prefixes, etc..., but if the db is incomplete it will forever wait for these updates to be received because there is no network swarm yet from which to grab the missing db nodes.

**Comment by equivalentideas** [comment]
> offending list is currently - @equivalentideas'
eb584b090c6160250e2b39285518e553f9fb0e7867536eabeb50310c7da9bbd7
Not sure why, but even when importing it - it gets stuck.

Let me know how to fix it when you can :)

Or I can just make a new one. I made a copy of the text in case this happened.

**Comment by e-e-e** [comment]
This bug is fixed by - https://github.com/e-e-e/hyper-reader/pull/38
@equivalentideas The issue was a version bump in the hyperdb dependency.  I still have not sorted out what has changed which caused the issue, but locking hyperdb to v3.1.0.

**Comment by e-e-e** [comment]
Try latest release here - https://github.com/e-e-e/hyper-reader/releases
